//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ShipperToQAD.QADShipper {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceINSEQShipperHttpBinding", Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
    public partial class ServiceINSEQShipperHttpService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback INSEQShipperOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceINSEQShipperHttpService() {
            this.Url = global::ShipperToQAD.Properties.Settings.Default.ShipperToQAD_QADShipper_ServiceINSEQShipperHttpService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event INSEQShipperCompletedEventHandler INSEQShipperCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ServiceINSEQShipper/INSEQShipper", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("INSEQShipperResponse", Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
        public INSEQShipperResponse INSEQShipper([System.Xml.Serialization.XmlElementAttribute("INSEQShipper", Namespace="http://yfaiesb/services/ServiceINSEQShipper")] INSEQShipper INSEQShipper1) {
            object[] results = this.Invoke("INSEQShipper", new object[] {
                        INSEQShipper1});
            return ((INSEQShipperResponse)(results[0]));
        }
        
        /// <remarks/>
        public void INSEQShipperAsync(INSEQShipper INSEQShipper1) {
            this.INSEQShipperAsync(INSEQShipper1, null);
        }
        
        /// <remarks/>
        public void INSEQShipperAsync(INSEQShipper INSEQShipper1, object userState) {
            if ((this.INSEQShipperOperationCompleted == null)) {
                this.INSEQShipperOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINSEQShipperOperationCompleted);
            }
            this.InvokeAsync("INSEQShipper", new object[] {
                        INSEQShipper1}, this.INSEQShipperOperationCompleted, userState);
        }
        
        private void OnINSEQShipperOperationCompleted(object arg) {
            if ((this.INSEQShipperCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INSEQShipperCompleted(this, new INSEQShipperCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
    public partial class INSEQShipper {
        
        private string vIA_CODEField;
        
        private string tRUCK_IDField;
        
        private string bOL_NBRField;
        
        private string pCK_SLP_NBRField;
        
        private string sITE_NBRField;
        
        private string sHIP_TSField;
        
        private string aDDR_CODEField;
        
        private string sERL_NBRField;
        
        private INSEQShipperType[] iNSEQShippersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string VIA_CODE {
            get {
                return this.vIA_CODEField;
            }
            set {
                this.vIA_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TRUCK_ID {
            get {
                return this.tRUCK_IDField;
            }
            set {
                this.tRUCK_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BOL_NBR {
            get {
                return this.bOL_NBRField;
            }
            set {
                this.bOL_NBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PCK_SLP_NBR {
            get {
                return this.pCK_SLP_NBRField;
            }
            set {
                this.pCK_SLP_NBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SITE_NBR {
            get {
                return this.sITE_NBRField;
            }
            set {
                this.sITE_NBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SHIP_TS {
            get {
                return this.sHIP_TSField;
            }
            set {
                this.sHIP_TSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ADDR_CODE {
            get {
                return this.aDDR_CODEField;
            }
            set {
                this.aDDR_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SERL_NBR {
            get {
                return this.sERL_NBRField;
            }
            set {
                this.sERL_NBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("INSEQShipper", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public INSEQShipperType[] INSEQShippers {
            get {
                return this.iNSEQShippersField;
            }
            set {
                this.iNSEQShippersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
    public partial class INSEQShipperType {
        
        private string sERL_NBR_TYPEField;
        
        private string sERL_NBRField;
        
        private string sERL_QTYField;
        
        private string lIN_CUST_ITEMField;
        
        private string lIN_VINField;
        
        private string lIN_PO_NBRField;
        
        private string rECID_PKGField;
        
        private string pARENTRECID_PKGField;
        
        private string rECID_PRTField;
        
        private string lIN_JOB_SEQ_AField;
        
        private string lIN_JOB_SEQ_BField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SERL_NBR_TYPE {
            get {
                return this.sERL_NBR_TYPEField;
            }
            set {
                this.sERL_NBR_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SERL_NBR {
            get {
                return this.sERL_NBRField;
            }
            set {
                this.sERL_NBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string SERL_QTY {
            get {
                return this.sERL_QTYField;
            }
            set {
                this.sERL_QTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LIN_CUST_ITEM {
            get {
                return this.lIN_CUST_ITEMField;
            }
            set {
                this.lIN_CUST_ITEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LIN_VIN {
            get {
                return this.lIN_VINField;
            }
            set {
                this.lIN_VINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LIN_PO_NBR {
            get {
                return this.lIN_PO_NBRField;
            }
            set {
                this.lIN_PO_NBRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string RECID_PKG {
            get {
                return this.rECID_PKGField;
            }
            set {
                this.rECID_PKGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PARENTRECID_PKG {
            get {
                return this.pARENTRECID_PKGField;
            }
            set {
                this.pARENTRECID_PKGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string RECID_PRT {
            get {
                return this.rECID_PRTField;
            }
            set {
                this.rECID_PRTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LIN_JOB_SEQ_A {
            get {
                return this.lIN_JOB_SEQ_AField;
            }
            set {
                this.lIN_JOB_SEQ_AField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LIN_JOB_SEQ_B {
            get {
                return this.lIN_JOB_SEQ_BField;
            }
            set {
                this.lIN_JOB_SEQ_BField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
    public partial class ERR_MSGType {
        
        private string mSG_IndexField;
        
        private string msg_DescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSG_Index {
            get {
                return this.mSG_IndexField;
            }
            set {
                this.mSG_IndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Msg_Desc {
            get {
                return this.msg_DescField;
            }
            set {
                this.msg_DescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
    public partial class ExceptionsType {
        
        private ERR_MSGType eRR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ERR_MSGType ERR_MSG {
            get {
                return this.eRR_MSGField;
            }
            set {
                this.eRR_MSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://yfaiesb/services/ServiceINSEQShipper")]
    public partial class INSEQShipperResponse {
        
        private string resultField;
        
        private ExceptionsType exceptionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ExceptionsType Exceptions {
            get {
                return this.exceptionsField;
            }
            set {
                this.exceptionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void INSEQShipperCompletedEventHandler(object sender, INSEQShipperCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INSEQShipperCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INSEQShipperCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public INSEQShipperResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((INSEQShipperResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591